name: SBOM upload

on:
    workflow_dispatch:
    push:
        branches: ["main"]

jobs:
    sbom-generation:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: advanced-security/sbom-generator-action@v0.0.1
              id: sbom
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - uses: actions/upload-artifact@v3.1.0
              with:
                  path: ${{steps.sbom.outputs.fileName }}
                  name: "sbom"

    sbom-upload:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write

        steps:
            - uses: actions/checkout@v3
            - name: SBOM upload
              uses: advanced-security/spdx-dependency-submission-action@v0.0.1
              with:
                  filePath: "sbom/"
